description: Projeto para teste automatizado pra Mobile utilizando RobotFramework
name: robot-mobile-stackspot
display-name: robot-mobile-stackspot
picture: stack.png
category: frontend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility: # Put a list of technologies compatible with the stack
  - Python 3.9
  - VS Code (extensão Robot Framework Intellisense)
  - Android Studio 2020.3.1
  - Xcode 13
  - Appium 1.20
about: docs/about.md
use-cases:
  - title: Configurar ambiente
    content: docs/use-case.md
#    stackfile: stackfiles/default.yaml

