description: Projeto para teste automatizado pra Mobile utilizando RobotFramework
name: robot-mobile-stackspot
display-name: robot-mobile-stackspot
picture: stack.png
category: backend
compatibility:
  - java
technologies: ["Docker"]
about: docs/about.md