description: Projeto para teste automatizado pra Mobile utilizando RobotFramework
name: robot-mobile-stackspot
display-name: robot-mobile-stackspot
picture: stack.png
category: fackend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility: # Put a list of technologies compatible with the stack
  - java
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies 
  - docker
about: docs/about.md
use-cases:
  - title: Configurar ambiente
    content: docs/use-case.md
#    stackfile: stackfiles/default.yaml

